set identity_insert Class on;

insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (1, 'Fighter', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (2, 'Rogue', 8, 'Small Melee Blades and Bludgeons', 'Rogues value stealth, speed, skill and timing; determining an opponent’s strong and weak points to plan an effective offensive.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (3, 'Ranger', 8, 'Short and Long Ranged', 'Rangers are natural woodsmen, able to track a target, pin them down and attack from a distance. Rangers connect with nature as they roam, gaining its protection and its friendship.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (4, 'Martial Artist', 12, 'Martial Arts, Hand Melee Bludgeons', 'Martial Artists are hand to hand warriors, eschewing weapons in the traditional sense, turning their body into a weapon. These warriors carefully choose their approach, taking each fight differently.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (5, 'Bard', 8, 'Any one declared category', 'Words are an inexhaustible source of magic; capable of both inflicting injury and remedying it. Bards use them to unbalance their enemies and make their friends stout of heart.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (6, 'Gunslinger', 7, 'Hand and Short Ranged', 'Gunslingers have mastered the newest inventions in ranged weaponry, centered around Black Powder. This grainy substance explodes when lit, used to push projectiles out of iron tubes at lethal speeds with unstoppable force.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (7, 'Ichorite', 2, null, 'An Ichorite manipulates their own life force and that of others. The techniques of Ichor exact incredible strain on the user’s body and must be used with great caution.', 0, 4, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (8, 'Druid', 2, null, 'Druids are mages who focus on natural energies. Few Druidic spells would be considered powerful, but they are prolific and versatile', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (9, 'Magus', 3, null, 'The Magus focuses on the ethereal magics, seeking celestial power. Magus spells are costly, but powerful.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Warlock', 3, null, 'Warlocks are mages venturing into the frontier of magic, focusing on the newly awakened Sources that have come forth from the shadows. ', 0, 0, 0, 0);

insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Arbiter', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Assassin', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Barrager', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Battle Mage', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Behemoth', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Berserker', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Black Belt', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Blackguard', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Blighter', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Buccaneer', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Chi Master', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Crimson Champion', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Gladiator', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Hunter', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Kirujen', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Ki Warrior', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Knight', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Mystic', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Ninja', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Sentinel', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Shaman', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Sohei', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Sorcerer', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Stalker', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Strider', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Troubadour', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Wizard', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);


insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (11, 'Academic', 0, null, 'Academics devote their lives to research, scrutinizing old dusty books in the dark corners of libraries; hoping to find that one small clue or offhand reference that will become the key to unraveling one of the mysteries of the world. These secrets, once discovered, are jealously guarded. Most Academics are willing to teach but convincing them to part with their greatest secrets is difficult if not impossible, as well as expensive. The most successful Academics are those willing and able to venture out of the safety of towns; searching for knowledge not yet stored in any library.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (12, 'Beefcake', 0, null, 'Muscular doesn’t quite describe you. More like, it’s a wonder that you can reach behind yourself with shoulders that huge. And you don’t even exercise… or do you?', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (13, 'Craftsman', 0, null, 'True Craftsmen take more than just a casual interest in their trade. This Profession produces Crafting items, described in greater detail near the end of the Rulebook.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (14, 'Hedgewitch', 0, null, 'While it may be useful to know how to rain fire down on monsters threatening the town, threats don’t happen every day. These Mages focus their time and effort on more practical spells.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (15, 'Merchant', 0, null, 'Money makes the world go ‘round, and the Merchants crack the whip', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (16, 'Outlaw', 0, null, 'Rulers of the underground, the alley, the dimly lit back room of the tavern, Outlaws make their way doing the jobs that no respectable person would consider', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (17, 'Tactician', 0, null, 'Tacticians are skilled in analyzing combat so as to improve the effectiveness of the forces they command. They scrutinize the enemy, find their weaknesses and reorganize their forces to secure victory..', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (18, 'Thief', 0, null, 'Keep those fingers sticky', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (19, 'Woodsman', 0, null, 'The untamed wilderness is the Woodsman’s home and the creatures therein are their family.', 1, 0, 0, 0);

set identity_insert Class off;