set identity_insert Class on;

insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (1, 'Fighter', 12, 'Any one declared category', 'The Fighter Class deals in melee combat. Its greatest strengths are in its consistency and its simplicity.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (2, 'Rogue', 8, 'Small Melee Blades and Bludgeons', 'Rogues value stealth, speed, skill and timing; determining an opponent’s strong and weak points to plan an effective offensive.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (3, 'Ranger', 8, 'Short and Long Ranged', 'Rangers are natural woodsmen, able to track a target, pin them down and attack from a distance. Rangers connect with nature as they roam, gaining its protection and its friendship.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (4, 'Martial Artist', 12, 'Martial Arts, Hand Melee Bludgeons', 'Martial Artists are hand to hand warriors, eschewing weapons in the traditional sense, turning their body into a weapon. These warriors carefully choose their approach, taking each fight differently.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (5, 'Bard', 8, 'Any one declared category', 'Words are an inexhaustible source of magic; capable of both inflicting injury and remedying it. Bards use them to unbalance their enemies and make their friends stout of heart.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (6, 'Gunslinger', 7, 'Hand and Short Ranged', 'Gunslingers have mastered the newest inventions in ranged weaponry, centered around Black Powder. This grainy substance explodes when lit, used to push projectiles out of iron tubes at lethal speeds with unstoppable force.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (7, 'Ichorite', 2, null, 'An Ichorite manipulates their own life force and that of others. The techniques of Ichor exact incredible strain on the user’s body and must be used with great caution.', 0, 4, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (8, 'Druid', 2, null, 'Druids are mages who focus on natural energies. Few Druidic spells would be considered powerful, but they are prolific and versatile', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (9, 'Magus', 3, null, 'The Magus focuses on the ethereal magics, seeking celestial power. Magus spells are costly, but powerful.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (10, 'Warlock', 3, null, 'Warlocks are mages venturing into the frontier of magic, focusing on the newly awakened Sources that have come forth from the shadows. ', 0, 0, 0, 0);

insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (11, 'Arbiter', 6, NULL, 'Technique, skill and adaptability often count for more than strength.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (12, 'Assassin', 3, 'Melee Hand and Small Blades', 'Assassins do one thing and do it very well - eliminate a target quickly and quietly, then escape into the shadows.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (13, 'Barrager', 3, 'Hand and Small Ranged', 'Barragers favor close-range thrown attacks as opposed to directly engaging in melee combat.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (14, 'Battle Mage', 3, 'Any one declared category', 'A mage who wishes to see the front lines of combat becomes a Battle Mage; training in melee combat to be able to hold their focus in the frenzy of combat and use their weapons as effectively as their hands to cast spells.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (15, 'Behemoth', 0, NULL, 'Behemoths are great hulking masses whose hide is as tough as the best Dwarven armor. Swords glance off their flanks as this colossus moves through the battlefield.', 0, 5, 0, 5);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (16, 'Berserker', 3, 'Great and Pole Bludegeons', 'Berserkers are the ultimate front-line warriors. Point them in a direction and watch them carve out a swathe of destruction, with little able to be done to slow or stop them. They live for combat, surrendering to the blind fury of their bloodlust, caring little for the consequences to themselves or others.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (17, 'Black Belt', 5, NULL, 'A Black Belt has turther refined the techniques of the Martial ARtist, heightening their offensive prowess and eschewing defense.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (18, 'Blackguard', 3, 'Short and Small Melee Blades', 'Blackguards focus their fighting on speed, rather than strength. A dozen light, fast blows can often be more effective than a single enormously heavy strike.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (19, 'Blighter', 2, NULL, 'Given time to prepare their ammunition, Blighters are powerhouses; able to store up many powerful spells and cast those and more at extreme range.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (20, 'Buccaneer', 5, 'Long Melee Bludegeons', 'When fighting ship to ship, mobility, positioning and range are paramount. The buccaneer has blended the perfect set of weapons and tactics for tight spaces, short distances and small groups.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (21, 'Chi Master', 2, NULL, 'Chi Masters have complete control of all the energy in their bodies, blending them together at will.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (22, 'Crimson Champion', 0, NULL, 'These masters of Ichor do not sacrifice their blood needlessly - constructing battle equipment and withholding the bloodshed until the right moment.', 0, 4, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (23, 'Gladiator', 3, 'Any one declared category', 'Gladiators specialize in dueling. Rarely seen with shields, Gladiators tent to prefer both hands on the hilt of a weapon - whether that means two smaller swords, one big hammer, or in rare cases of immense strength and dexterity, a pair of polearms.', 0, 0, 5, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (24, 'Hunter', 4, 'Long and Great Ranged', 'Hunter specialize in their favorite prey - tracking them down and taking them down. Their skills with ranged weapons are so honed that even a wide shield presents no challenge.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (25, 'Kirujen', 3, NULL, 'A Kirujen specializes in the classical healing arts; prowling the edges of a battlefield, searching for the wounded. With a pure heart and peaceful intentions, some Kirujen venture into the center of battle, ignoring the blades and arrows whizzing past their heads, their only goal to help the injured.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (26, 'Ki Warrior', 3, NULL, 'Ki Warriors have an unqenchable thirst for combat. Their fighting spirit is unbreakable, driving their bodies far past their limits and even through the grave.', 0, 2, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (27, 'Knight', 0, 'Short Melee Bludgeons and Blades', 'A Knight is an exceptionally sturdy warrior clad head to toe in armor, often leading groups of weaker swordsmen into glorious battle.', 0, 0, 5, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (28, 'Mystic', 3, 'Small Melee Bludgeons and Short Melee Blades', 'Magic poses little threat to the Mystic, who specializes in foiling Mages.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (29, 'Ninja', 0, 'Any one declared category', 'Ninjas specialize in subterfuge - carrying out orders to sabotage enemy equipment, and able to quickly incapacitate anyone in their way. Ninjas take pride in their ability to adapt to any situation.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (30, 'Sentinel', 6, 'Pole Melee Blades and Bludgeons', 'The guardsman, the gatekeeper; these people fight to the last to protect their Post.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (31 'Shaman', 0, NULL, 'You''ve got to fell the mana moving through you, like the beat of a drum.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (32, 'Sohei', 5, NULL, 'A Sohei spends their life in battle, or training for it. They dance through a battlefield redirecting or shrugging off most strikes that come their way.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (33, 'Sorcerer', 0, NULL, 'Sorcerers understand magic far in excess of most mages. These masters of quick casting more easily harness pure Mana and can manipulate latent magic inside of themselves.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (34, 'Stalker', 3, 'Long and Small Melee Blades', 'Placeholder for Stalker', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (35, 'Strider', 5, 'Any one declared category', 'The Strider wanders the wilderness alone, his wizened eyes the most difficult to fool - ambushing him is nearly impossible. Even if you manage it, the Strider is perfectly capable of fighting several enemies at once.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (36, 'Troubadour', 7, NULL, 'The Troubadour takes center stage easily, whether or not there''s a physical stage. Wherever they stand becomes the center of attention for as long as they wish.', 0, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (37, 'Wizard', 0, NULL, 'Wizards are masters of prepared magic. Their Spell Seals are stronger, and they make Ritual Magic look like child''s play. Their unique Rituals will force an adventurer to make some difficult choicesabout what to do with their Spirit Presence.', 0, 0, 0, 0);


insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (38, 'Academic', 0, null, 'Academics devote their lives to research, scrutinizing old dusty books in the dark corners of libraries; hoping to find that one small clue or offhand reference that will become the key to unraveling one of the mysteries of the world. These secrets, once discovered, are jealously guarded. Most Academics are willing to teach but convincing them to part with their greatest secrets is difficult if not impossible, as well as expensive. The most successful Academics are those willing and able to venture out of the safety of towns; searching for knowledge not yet stored in any library.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (39, 'Beefcake', 0, null, 'Muscular doesn’t quite describe you. More like, it’s a wonder that you can reach behind yourself with shoulders that huge. And you don’t even exercise… or do you?', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (40, 'Craftsman', 0, null, 'True Craftsmen take more than just a casual interest in their trade. This Profession produces Crafting items, described in greater detail near the end of the Rulebook.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (41, 'Hedgewitch', 0, null, 'While it may be useful to know how to rain fire down on monsters threatening the town, threats don’t happen every day. These Mages focus their time and effort on more practical spells.', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (42, 'Merchant', 0, null, 'Money makes the world go ‘round, and the Merchants crack the whip', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (43, 'Outlaw', 0, null, 'Rulers of the underground, the alley, the dimly lit back room of the tavern, Outlaws make their way doing the jobs that no respectable person would consider', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (44, 'Tactician', 0, null, 'Tacticians are skilled in analyzing combat so as to improve the effectiveness of the forces they command. They scrutinize the enemy, find their weaknesses and reorganize their forces to secure victory..', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (45, 'Thief', 0, null, 'Keep those fingers sticky', 1, 0, 0, 0);
insert into Class (ClassId, ClassName, BaseStamina, WeaponProf, Description, Profession, BaseHp, BaseWearLimit, BaseNatArmor) values (46, 'Woodsman', 0, null, 'The untamed wilderness is the Woodsman’s home and the creatures therein are their family.', 1, 0, 0, 0);

set identity_insert Class off;